### ISSUE TITLE
Infinite loop on current channel

### ISSUE THREAD

**Issue by thommay** [chef-cookbooks/chef_client_updater#10]
With only:
```
chef_client_updater 'current' do
  channel 'current'
end
```

chef will get endlessly re-execed, since we don't check that what we're running is the latest, but simply blindly install.

**Comment by dkowis** [comment]
I have found this behavior on 'stable' channel as well as well. I've noticed that it's *always* updating the chef-client, and so the run never actually finishes. It dies with an error if it is kill'd.

**Comment by tas50** [comment]
This has been fixed on master by properly handling :latest vs. 'latest'
