### ISSUE TITLE
Unsuccessful upgrades when other processes have open handles in chef_install_dir

### ISSUE THREAD

**Issue by Happycoil** [chef-cookbooks/chef_client_updater#110]
### Cookbook version
3.2.6

### Platform Details
Windows

### Scenario:
A frequent problem we encounter when trying to use this cookbook is the upgrade script failing to remove the chef install dir due to open file handles. This is usually because of AV/endpoint protection or similar software.

This causes the upgrade script to fail and chef-client is left in an inoperable state requiring manual intervention.

### Steps to Reproduce:
Open a file in the chef install dir in another process and run the cookbook.

**Comment by gsreynolds** [comment]
https://github.com/chef-cookbooks/chef_client_updater/issues/74 also seems relevant as `chef-log.dll` is the file often locked with open file handles.

**Comment by sardmang** [comment]
#74 seems relevant, still having issues with chef-log.dll at times.
