### ISSUE TITLE
Can't downgrade to desired version on Windows

### ISSUE THREAD

**Issue by anniehedgpeth** [chef-cookbooks/chef_client_updater#120]
### Cookbook version
3.3.2

### Chef-client version
14.0.190

### Platform Details
Azure
Windows Server 2012r2

### Scenario:
When I try to downgrade chef client from `14.1.190` to `12.18.31`, it never takes me to `12.18.31`. It will always downgrade to another lower version, but never the one I specified in my attribute, which puts it in a loop where it’s never finished completing the downgrade because it keeps trying to get to the version specified in the attribute. Once it was `12.8.1`, another time `13.8.5`, this time `13.4.24`. 
The downgrade works fine on my Ubuntu, though. 

### Steps to Reproduce:

Recipe:

```
node.default['chef_client_updater']['prevent_downgrade'] = true
desired_chef_version = node['our_wrapper']['chef_version']

chef_client_updater "Install #{desired_chef_version}" do
  version desired_chef_version
  post_install_action node['chef_client_updater']['post_install_action']
  prevent_downgrade node['chef_client_updater']['prevent_downgrade']
  exec_command 'chef-client'
end
```

Attributes:

```
default['internal']['chef']['interval']                         = 30
default['our_wrapper']['chef_version']                 = '12.18.31'
force_override['omnibus_updater']['disabled']                = true
default['chef_client_updater']['upgrade_delay']              = 180
force_override['chef_client']['log_file']                    = nil

if platform?('windows')
  default['chef_client']['conf_dir'] = 'C:/chef'
  force_override['chef_client_updater']['post_install_action'] = 'exec'
end
```

### Expected Result:
I would expect the chef client to be downloaded to the version I specified in the attribute as it did for the Ubuntu.

### Actual Result:
It seemingly randomly chooses a lower version to downgrade other than the version I specified. Once it was `12.8.1`, another time `13.8.5`, this time `13.4.24`. 
The downgrade works fine on my Ubuntu, though.

**Comment by stuartpreston** [comment]
@anniehedgpeth, I just tested this with the latest version of the cookbook (3.3.4) and was able to downgrade successfully from 14.0.190 (manually installed) to 12.18.31 (downgraded via cookbook)

First of all in your recipe you'll need to pass `false` to the prevent_downgrade attribute, i.e. the first line of your recipe should read:

```node.default['chef_client_updater']['prevent_downgrade'] = false```

FYI this version of the cookbook will also show additional output in `c:\opscode\chef_upgrade.log` - and also requires either internet access to download the requires Sysinternals Handle tool (used to kill off locked file handles), setting an attribute with the HTTP location of the tool, or putting handle.exe in your Chef::Config[:file_cache_path] directory prior to running the recipe. 

![image](https://user-images.githubusercontent.com/6384654/40723925-cd68d746-6417-11e8-84f1-5ad4ba8e3ada.png)

Please give it a go and let me know if you get any further.

**Comment by anniehedgpeth** [comment]
This was a copy/paste error (just confirmed on my Chef server), but yes, I did have it on false:
`node.default['chef_client_updater']['prevent_downgrade'] = false`

I had just changed it back after I was done testing.

**Comment by anniehedgpeth** [comment]
@stuartpreston I tested it again, this time on v3.3.4 of the cookbook. One time it worked (properly downgraded to the desired version), and three times it didn't (tried to downgrade to another random version). One of the times that it didn't, this was the only thing in the chef_upgrade log:

```
[*] Destroying open Chef handles.
[*] Completed destroying open Chef handles.
```
This was the stacktrace:
```
Generated at 2018-05-30 19:07:32 +0000
SystemExit: exit
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `exit'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `run_post_install_action'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:426:in `block (2 levels) in class_from_file'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/provider.rb:202:in `converge_by'
c:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:425:in `block in class_from_file'
(eval):2:in `block in action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/provider.rb:211:in `instance_eval'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_update'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/runner.rb:98:in `each'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/runner.rb:97:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:710:in `catch'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:710:in `converge'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/client.rb:286:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/lib/chef/application.rb:59:in `run'
c:/opscode/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.24-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/push-jobs-client/bin/chef-client:58:in `load'
c:/opscode/push-jobs-client/bin/chef-client:58:in `<main>'
```

**Comment by stuartpreston** [comment]
@anniehedgpeth I'm puzzled by how you got here.  You start by saying that you're trying downgrade Chef Client, but as you can see in the stack trace, the chef-client from the push-jo client appears to be invoked!  So I'm totally confused by how you got to this stage.  Could you outline the steps and outcomes, also could you comment on the state of the machine at the time of the first "downgrade" (especially whether any intermediate versions of Chef Client would have been installed somehow) ?

**Comment by dheerajd-msys** [comment]
@anniehedgpeth Could you please confirm about https://github.com/chef-cookbooks/chef_client_updater/issues/120#issuecomment-393562827 ?

**Comment by anniehedgpeth** [comment]
Sorry, I must've found a workaround and had gotten too busy to dig further into this. 

I don't know why the stack trace says that chef-client from the push-jobs-client was invoked. It wasn't invoked purposely. Perhaps there was a bug in that version of push jobs that caused it to run? Not sure. 

No, no intermediate versions of Chef Client would have been installed. We didn't even use or want v13 at the time. We went straight from 12 to 14.

**Comment by dheerajd-msys** [comment]
Hi @anniehedgpeth,
Tried to verify from my end and chef downgrade is working perfectly fine with latest cookbook **_v3.7.3_**.
```
[2019-12-19T06:31:06+00:00] INFO: powershell_script[name] ran successfully

      - execute "C:\windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -Executio
nPolicy Bypass -InputFormat None -File "C:/Users/azuree/AppData/Local/Temp/2/chef-script20191219-4860-1h3ipwv.ps1"
    - upgrade chef 14.0.190 to 12.18.31[2019-12-19T06:31:06+00:00] WARN: New chef-client installed and exit is allowed.
Forcing chef exit!


PS C:\Users\azuree> chef-client -v
Chef: 12.18.31
PS C:\Users\azuree>
```
Closing this issue.
