### ISSUE TITLE
exit kitchen cleanly

### ISSUE THREAD

**Issue by acqant** [chef-cookbooks/chef_client_updater#127]
### Cookbook version
3.4.0

### Chef-client version
13.3.42

### Platform Details
ubuntu 14.04 iso

### Scenario:
upgrade chef-client.
Test upgrade in kitchen
Don't exit 1
### Steps to Reproduce:
Test in kitchen with exec. It switches to kill

### Expected Result:
Expecting the cookbook to not send a failure exit

### Actual Result:
chef-client-updater exits with error

We can't put this in jenkins since the tests will fail.  Should have some test-kitchen options to exit cleanly.

**Comment by acqant** [comment]
Been playing with this for awhile.
Thinking maybe a third option called 'kitchen' will work to preserve the exec option.

**Comment by donwlewis** [comment]
Sad that the documentation says that this should work but still doesn't....

**Comment by donwlewis** [comment]
Nevermind.  My bad.  This appears to be more of an older chef-client problem thingy...

**Comment by dheerajd-msys** [comment]
@acqant @donwlewis I was just wondering if you are following https://github.com/chef-cookbooks/chef_client_updater#test-kitchen-testing to test the cookbook with `post_install_action` option set to `exec`. Please confirm.

**Comment by dheerajd-msys** [comment]
@acqant @donwlewis Can we close this issue if this is no longer bugging you? Please check https://github.com/chef-cookbooks/chef_client_updater/issues/127#issuecomment-555921940 .

**Comment by dheerajd-msys** [comment]
@acqant @donwlewis Please check and confirm ^ .
Thank you!!

**Comment by acqant** [comment]
yeah close it up
