### ISSUE TITLE
License Attribute not working for version 3.7.x 

### ISSUE THREAD

**Issue by iasllani** [chef-cookbooks/chef_client_updater#170]
You'll want to update to the 3.7.x cookbook and then you can set license acceptance via this attribute: https://github.com/chef-cookbooks/chef_client_updater/blob/master/attributes/default.rb#L57

_Originally posted by @tas50 in https://github.com/chef-cookbooks/chef_client_updater/issues/168#issuecomment-557214360_

**To be clear, the attribute was available in the 3.6.0 version I ran, I set it to both, accept and accept-no-persist.

With 3.7.1 I'm getting a new error:**

resolving cookbooks for run list: ["chef_client_updater"]
Synchronizing Cookbooks:

chef_client_updater (3.7.1)
Installing Cookbook Gems:
Compiling Cookbooks...
←[0m
================================================================================
Recipe Compile Error in C:/chef/cache/cookbooks/chef_client_updater/providers/de
fault.rb
SyntaxError
C:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:142: syntax err
or, unexpected '.'
version ? version.to_s.split(': ').last&.strip : nil
^
C:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:144: syntax err
or, unexpected keyword_end, expecting end-of-input

Platform:
x64-mingw32

←[0m
Running handlers:
[2019-11-27T09:03:27-05:00] ERROR: Running exception handlers
Running handlers complete
[2019-11-27T09:03:27-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2019-11-27T09:03:27-05:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stack
trace.out
[2019-11-27T09:03:27-05:00] FATAL: Please provide the contents of the stacktrace
.out file if you file a bug report
[2019-11-27T09:03:27-05:00] FATAL: SyntaxError: C:/chef/cache/cookbooks/chef_cli
ent_updater/providers/default.rb:142: syntax error, unexpected '.'
version ? version.to_s.split(': ').last&.strip : nil
^
C:/chef/cache/cookbooks/chef_client_updater/providers/default.rb:144: syntax err
or, unexpected keyword_end, expecting end-of-input

**Comment by Nimesh-Msys** [comment]
Not only the compilation but also the complete execution seems to be running fine at my end.
Could you please provide certain details like chef-client version, the actual recipe and the ruby version. Noted the platform: x64-mingw32. It would really be helpful if you could tell us the output of `chef -v`.

**Comment by iasllani** [comment]
Running default recipe of the cookbook version 3.7.1,
3.6.0 would help me update from 12.9.41 go 15.2.20, but the license would still have to be accepted by the user through the console, despite setting the attribute for the license to 'accept' 
Testing on windows server 2008 r2

-v output:
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\iasllani-c>chef-client -v
Chef: 12.9.41

**Comment by danielcbright** [comment]
@Nimesh-Msys it looks like this command is not working properly in a WIndows environment:

https://github.com/chef-cookbooks/chef_client_updater/blob/master/providers/default.rb#L470

even when you run it manually, it still asks to accept the license, I recommend changing this to add the license directly to the `config.rb` but that's my opinion :)

**Comment by Nimesh-Msys** [comment]
Agreed, I tried upgrading chef-client 12.10.24 to 15.6.10(latest stable till date) on Microsoft Windows Server 2012 R2 Datacenter with all three possibilities `default['chef_client']['chef_license']` as `nil`, `accept` and `accept-no-persist`. It still asks for accepting the license. We are working on it.
