### ISSUE TITLE
License agreement not skipped when upgrading from chef-client v13 to v15

### ISSUE THREAD

**Issue by MrCyrus** [chef-cookbooks/chef_client_updater#203]
Attribute setting:
   default['chef_client']['chef_license'] = 'accept'
is not working. 

We've an environment with some old V13 chef-clients I'm trying to upgrade to v15 and though this cookbook does indeed upgrade to the specified version 15, the above line in an attributes/default.rb file is not working as expected.

When I manually run chef-client, chef_client_updater is killing the currently running chef-client after upgrading the client (as expected), but I'd have expected to see files in /etc/chef/accepted_licenses to be created so the next run of chef-client v15 would run without prompting a user for anything, but when I run chef-client manually a 2nd time I'm being prompted to accept the license agreement.

Server: RHEL 7.8
Upgrading from chef 13.6.4 to 15.11.3

**Comment by seeven-kathan** [comment]
Hello, 
Having same issue.

Regards,
Seeven

**Comment by dheerajd-msys** [comment]
Hi @MrCyrus we are working on this issue, in the meantime could you please provide us the console log during chef-client execution?

Thanks

**Comment by MrCyrus** [comment]
Some additional information that might help:
RHEL 6 - since this still uses /etc/init.d to start/stop services, during an upgrade this cookbook added an entry to root's crontab to run chef-client about 5 minutes after the chef-client run (giving it time to upgrade). The crontab entry had the correct accept license agreement. When the cron ran, it then removed itself from cron and the license agreement was accepted correctly. So RHEL 6 worked.

RHEL7/RHEL8: chef-client runs and does the upgrading, but for some reason the service is NOT auto-restarting chef-client.

After the self-upgrade, I ran:
service chef-client status -l

● chef-client.service - Chef Client daemon
   Loaded: loaded (/etc/systemd/system/chef-client.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2020-07-02 14:39:18 MDT; 8min ago
  Process: 10914 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 13093 ExecStart=/usr/bin/chef-client -c $CONFIG -i $INTERVAL -s $SPLAY $OPTIONS (code=exited, status=172)
 Main PID: 13093 (code=exited, status=172)

Jul 02 14:39:18 server systemd[1]: chef-client.service: main process exited, code=exited, status=172/n/a
Jul 02 14:39:18 server systemd[1]: Unit chef-client.service entered failed state.
Jul 02 14:39:18 server systemd[1]: chef-client.service failed.
Jul 02 14:39:18 server systemd[1]: chef-client.service holdoff time over, scheduling restart.
Jul 02 14:39:18 server systemd[1]: Stopped Chef Client daemon.
Jul 02 14:39:18 server systemd[1]: start request repeated too quickly for chef-client.service
Jul 02 14:39:18 server systemd[1]: Failed to start Chef Client daemon.
Jul 02 14:39:18 server systemd[1]: Unit chef-client.service entered failed state.
Jul 02 14:39:18 server systemd[1]: chef-client.service failed.

**Comment by jgrenoble** [comment]
I just ran into this issue as well while running RHEL 7 and CentOS 7 and upgrading from 14.x to 15.11.8. I had node attributes set to accept the Chef license but it didn't seem to work as the chef-client service won't start presumably due to the license agreement.

Looking forward to PR being merged.

**Comment by kmf** [comment]
same here would love the PR to be merged ....

Please @lamont-granquist you are a our only hope.   

![please](https://user-images.githubusercontent.com/78700/88177302-ecb0f680-cc28-11ea-83c7-321ceb51ed63.gif)
