### ISSUE TITLE
Errno::ENOENT: No such file or directory @ realpath_rec - C:/opscode/chef

### ISSUE THREAD

**Issue by ABrehm264** [chef-cookbooks/chef_client_updater#32]
### Cookbook version
2.0.1

### Chef-client version
latest (via TestKitchen)

### Platform Details
TestKitchen
Windows Server 2012r2

### Scenario:
Trying to see if I can downgrade chef-client from chef13 to chef11 or chef12

### Steps to Reproduce:
Metadata:
depends 'windows', '~> 3.1.1'
depends 'chef-client', '~> 8.1.2'
depends 'chef_client_updater', '~> 2.0.1'

Attributes File:
default['chef_client_updater']['version'] = '12.20.3'
default['chef_client_updater']['prevent_downgrade'] = false
default['chef_client_updater']['post_install_action'] = 'kill'

recipe:
include_recipe 'chef_client_updater::default' # updates chef client
include_recipe 'chef-client::default'

### Expected Result:
Error to not happen and chef version in C:/opscode/chef to be the version that I specified.

### Actual Result:
             - moving all files under c:/opscode/chef.upgrade to c:/opscode/chef
             ================================================================================
             Error executing action `update` on resource 'chef_client_updater[update chef-client]'
             ================================================================================

             Errno::ENOENT
             -------------
             No such file or directory @ realpath_rec - C:/opscode/chef

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb

       20: chef_client_updater 'update chef-client' do
       21:   channel node['chef_client_updater']['channel']
       22:   version node['chef_client_updater']['version']
       23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
       24:   post_install_action node['chef_client_updater']['post_install_action']
       25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_updater']['download_url_override']
       26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
       27: end

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/recipes/default.rb:20:in `from_file'

             chef_client_updater("update chef-client") do
        action [:update]
        updated true
        updated_by_last_action true
        default_guard_interpreter :default
        declared_type :chef_client_updater
        cookbook_name "chef_client_updater"
        recipe_name "default"
        channel "stable"
        version "12.20.3"
        prevent_downgrade false
        post_install_action "kill"
             end

             System Info:
             ------------
             chef_version=13.1.31
             platform=windows
             platform_version=6.3.9600
             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client

         Running handlers:
       [2017-06-19T09:07:53-07:00] ERROR: Running exception handlers
         Running handlers complete
       [2017-06-19T09:07:53-07:00] ERROR: Exception handlers complete
         Chef Client failed. 1 resources updated in 23 seconds
       [2017-06-19T09:07:53-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-06-19T09:07:53-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-06-19T09:07:53-07:00] FATAL: Errno::ENOENT: chef_client_updater[update chef-client] (chef_client_updater::default line 20) had an error: Errno::ENOENT: No such file or directory @ realpath_rec - C:/opscode/chef
    $$$$$$           + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
    $$$$$$           + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: 1 actions failed.
    >>>>>>     Converge failed on instance <default-win-2012>.  Please see .kitchen/logs/default-
    win-2012.log for more details
    >>>>>> ----------------------
    >>>>>> Please see .kitchen/logs/kitchen.log for more details
    >>>>>> Also try running `kitchen diagnose --all` for configuration

As far as I can tell, it's moving the c:/opscode/chef folder to c:/opscode/chef.snapshot (or whatever) and then the install script is failing to update c:/opscode/chef because it doesn't exist or something.

**Comment by lamont-granquist** [comment]
```
   [2017-06-19T09:07:53-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
   [2017-06-19T09:07:53-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
```

the contents of that file would be useful

**Comment by ABrehm264** [comment]
I'll see if I can get that for you. The main problem seemed to have been that the update script was needing c:/opscode/chef to exist, after the code moved it. But yeah, I'll see what I can do.

**Comment by lamont-granquist** [comment]
I would think that would have produced a Mixlib::ShellOut exception, not the Errno::ENOENT which is showing up.  The stacktrace.out would shed more light on that.

**Comment by ABrehm264** [comment]
Here ya go:
[stacktrace.out.txt](https://github.com/chef-cookbooks/chef_client_updater/files/1106769/stacktrace.out.txt)

**Comment by lamont-granquist** [comment]
yeah the error formatting is blowing up because it expects the files in the stack trace to exist which is masking everything that is going on....

**Comment by lamont-granquist** [comment]
```

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Windows/Temp/chef-script20170627-3004-wwbo6o.ps1" ----
STDOUT: Installing chef from C:\Users\vagrant\AppData\Local\Temp\chef-client-12.20.3-1-x64.msi
STDERR: C:\Windows\Temp\chef-script20170627-3004-wwbo6o.ps1 : msiexec was not 

successful. Received exit code 1603

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 

   tion

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 

   n,chef-script20170627-3004-wwbo6o.ps1
---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Windows/Temp/chef-script20170627-3004-wwbo6o.ps1" ----
Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Windows/Temp/chef-script20170627-3004-wwbo6o.ps1" returned 1
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:289:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:276:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/mixin/shell_out.rb:120:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider/execute.rb:58:in `block in action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider.rb:202:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider/execute.rb:56:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider/script.rb:64:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider/windows_script.rb:57:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider/powershell_script.rb:35:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb:215:in `execute_install_script'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_client_updater/providers/default.rb:235:in `block (2 levels) in class_from_file'
```

that is a lot more relevant, although I'm not parsing exactly what went wrong...

**Comment by lamont-granquist** [comment]
so to clarify: "No such file or directory @ realpath_rec - C:/opscode/chef" is a puke coming from the error formatter.  once the exception has been thrown the error formatter then goes and gets very upset over its files having disappeared.  that is somewhat unfortunate (also not very easily fixable, although we could do more defensive coding in the error formatter, but that doesn't help anyone upgrading from a version of chef that is already released...)

the actual error is that snippet that I pasted above.  that doesn't (or doesn't obviously) reference any issues about c:\opscode\chef disappearing on it.

**Comment by lamont-granquist** [comment]
@wrightp i'm not sure if you've got any thoughts on this one.  i think we're going to need a windows expert here and that's not me.  its possible that this is related to a failed uninstall of the prior chef version (possibly due to the directory being moved) but we have to do that because we're running the thing which is being upgraded and if we nuke the files out from under it, the running chef-client gets very annoyed, so we had to go down the route of moving the files away...

googling "exit code 1603" seems to indicate it could be simple permissions issue, but again i don't know what to do about it, don't even know where to start debugging...

**Comment by lamont-granquist** [comment]
also paging in @mwrock @btm and @NimishaS

**Comment by mwrock** [comment]
The best way to debug `1603` errors is to have `msiexec` send debug logging to a file. Almost always that output will say what specifically went wrong.

**Comment by croffe** [comment]
I was seeing the same issue.  I believe this is fixed by mixlib-install 3.3.1 - https://github.com/chef/mixlib-install/pull/219 

I've tested this in Windows 2012 R2

**Comment by lamont-granquist** [comment]
@ABrehm264 can you confirm that the mixlib-install 3.3.1 release yesterday fixes this?

**Comment by ABrehm264** [comment]
Sorry for not responding earlier, I've been out of pocket :(

That does not seem to have fixed my problem :(

Here's what I updated my recipe to:
./recipes/default.rb
```
chef_gem 'mixlib-install' do
  version '3.3.1'
  action :install
end

include_recipe 'chef_client_updater::default' # updates chef client
include_recipe 'chef-client::default'
```

gem list on my box:
![image](https://user-images.githubusercontent.com/12091031/28021333-81266324-6555-11e7-9081-371a48ee7e7b.png)

Here's the stack trace:
[stacktrace.out.txt](https://github.com/chef-cookbooks/chef_client_updater/files/1135737/stacktrace.out.txt)

When I get the chance, I'll see if I can dig into this a little bit more, but yeah, I think something weird is going on with something that mixlib is doing. (IDK if it's the install script that's downloaded or what)

**Comment by tas50** [comment]
I believe there's a high likelihood that this issue has been resolved with the latest release of this cookbook that uses the new mixlib-install. If you're still having these problems with the 3.1 release feel free to open this issue back up.
