### ISSUE TITLE
HTTP Proxy overridden in Windows update

### ISSUE THREAD

**Issue by rlaveycal** [chef-cookbooks/chef_client_updater#39]
### Cookbook version
2.0.2

### Chef-client version
12.13.37

### Platform Details
Windows 2012R2

### Scenario:
We have a corporate web proxy. The http_proxy environment variable is set. When Chef is run it fails.

### Steps to Reproduce:
 1. Install Chef 12.13
 1. Run Chef against `chef_client_updater::default`

### Expected Result:
The Chef run to complete without error, updating the client if appropriate

### Actual Result:
```
      STDOUT: There was an error:
        Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
        Unable to connect to the remote server
        No connection could be made because the target machine actively refused it 151.101.16.65:443
      STDERR: C:\Users\vagrant\AppData\Local\Temp\chef-script20170627-3988-zi9j61.ps1 : Failed to download from
      https://omnitruck.chef.io/stable/chef/metadata?v=12.21.1&p=windows&pv=2012r2&m=x86_64.
          + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chef-script20170627-3988-zi9j61.ps1
```

### Diagnostics

Hunting around in the code leads me to believe the problem is in `mixlib-install-3.3.0\lib\mixlib\install\generator\powershell\scripts\install_project.ps1` which contains the line

```
  # Set http_proxy as env var
  $env:http_proxy = $http_proxy
```

to override the environment proxy with the value of the script's local parameter. The problem is that this parameter is derived from the options hash used to instantiate the `Mixlib::Install` object which doesn't set it. Without a `String::IsNullOrEmpty()` check the effect is to disable the proxy setting

Adding a couple of `write-host`s above this line shows this:
```
env:http_proxy = http://proxy1.uk.webscanningservice.com:3128
http_proxy =
```

I'd love to do a PR but I'm slammed with other stuff.

**Comment by lamont-granquist** [comment]
this is actually a dup of chef/mixlib-install#201 and chef/mixlib-install#204 and details should probably be put there.

until mixlib-install supports proxies, this cookbook can't support proxies, so work and discussion really needs to land over in that repo.
