### ISSUE TITLE
chef-client run doesn't finish

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef-cookbooks/chef_client_updater#40]
### Cookbook version
2.0.2

### Chef-client version
Was `12.15.19` Installed `13.1.31`

### Platform Details
Windows 2012 R2 Azure Build

### Scenario:
Upgrade the chef-client on windows

### Steps to Reproduce:
```
Starting Chef Client, version 12.15.19
resolving cookbooks for run list: ["chef_client_updater"]
Synchronizing Cookbooks:
  - chef_client_updater (2.0.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: chef_client_updater::default
  * chef_client_updater[update chef-client] action update
    - upgrading rubygems to 2.6.11 was 2.6.7
    * chef_gem[mixlib-install] action install
      - install version >= 3.2.1 of package mixlib-install
    - moving all files under c:/opscode/chef to c:/opscode/chef.upgrade
    * powershell_script[name] action run
      - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -Executio
nPolicy Bypass -InputFormat None -File "C:/Users/recovery/AppData/Local/Temp/2/chef-script20170627-4028-f3w3zi.ps1"
[2017-06-27T15:28:13+00:00] WARN: Replacing ourselves with the new version of Chef to continue the run.
[2017-06-27T15:28:19+00:00] WARN: Chef client 4028 is running, will wait for it to finish and then run.
[2017-06-27T15:28:19+00:00] WARN: Chef client 4028 is running, will wait for it to finish and then run.
```

### Expected Result:
chef-client run to end or restart

### Actual Result:
From what I can tell looking around the system, the old client was move to the .upgrade folder, the new version msi was downloaded and installed (add remove programs lists version 13.1.31 as installed. but the chef-client run (process 4028) doesn't ever finish?  there is nothing more in the log so I don't know where else to look to find out why the process has hung

After an hour I killed the process (4028) and the chef-client immeditaly kicked off another run using 13.1.31 removed the .upgrade folder

As a side there was still one file left

```
C:\opscode\chef.upgrade\embedded\lib\ruby\gems\2.3.0\gems\chef-12.15.19-universal-mingw32\ext\win32-eventlog\chef-log.dll
```
preventing it from removing fully

**Comment by username-is-already-taken2** [comment]
As I have a couple of machines in Azure (same template and version of Chef I thought I would enable debug within the `client.rb.`

Might be significate but there was a couple of extra lines, going to sleep and the run of ohai.

```
[2017-06-27T16:02:52+00:00] INFO: powershell_script[name] ran successfully
[2017-06-27T16:02:52+00:00] WARN: Replacing ourselves with the new version of Chef to continue the run.
[2017-06-27T16:02:58+00:00] DEBUG: Sleeping for 0 seconds
[2017-06-27T16:02:58+00:00] DEBUG: Running Ohai with the following configuration: {}
[2017-06-27T16:02:58+00:00] WARN: Chef client 5032 is running, will wait for it to finish and then run.
```

Hope that helps

**Comment by tas50** [comment]
@username-is-already-taken2 If you set the post install action to kill this will probably resolve itself. The old client hasn't been killed and the new client won't run if the pid file for the previous client is still active.

**Comment by username-is-already-taken2** [comment]
After a reboot, re-running the chef-client removed the file that was kicking around.

**Comment by tas50** [comment]
A reboot would achieve the same end result of killing the old process. If you use kill as the post install action this will probably work as expected without a reboot. I'll close this out. Feel free to open it back up if you give that a try and it doesn't work.

**Comment by lamont-granquist** [comment]
we might want to document this in the README, i also saw this happen a bunch but never got around to tracking it down...

**Comment by username-is-already-taken2** [comment]
Hi @tas50 I tried the kill action method on another box and that worked fine.  My thought is that maybe you should consider changing the default action to kill? (rather than exec) 
In Exec mode the chef-client is hung and won't run again until terminated or the system is rebooted.  In windows the chef-client installation creates a schedule tasks which will terminate a long running process after 3days.
![image](https://user-images.githubusercontent.com/13700297/27637323-397b0554-5c07-11e7-81ce-4530bba0054b.png)

That would be a long time to wait, just my 5p worth :)
