### ISSUE TITLE
chef-client runs and exits successfully but the process hangs around afterwards

### ISSUE THREAD

**Issue by jrieck1991** [chef-cookbooks/chef_client_updater#45]
### Cookbook version
chef_client_updater 1.0.2

### Chef-client version
chef-client 12.17.44

### Platform Details
CentOS 6.9

### Scenario:
chef-client runs and exits successfully but the process hangs around afterwards, this doesn't stop chef-client from running again but it does trigger alerts on our side for the lingering process.

### Steps to Reproduce:
It only happens on a small section of our nodes, I have no idea how to reproduce. I have an inkling that due to upgrading chef-client the old pid gets left and doesn't get overwritten with the new version chef-client pid.

### Expected Result:
chef-client doesn't show up with ps -ef

### Actual Result:
chef-client is show in ps -ef

**Comment by lamont-granquist** [comment]
does switching the post install action to 'kill' fix it? 

@tas50 i'm kind of wondering if that default needs to be flipped.

**Comment by tas50** [comment]
I just came here to mention that we should probably change it to kill. We certainly need some more detailed documentation about the importance of the post install action and making sure you have the right setting. It seems to be causing a lot of confusion. I wonder if we could make it smarter about just doing the right thing.

**Comment by lamont-granquist** [comment]
so if we want to do that we should probably do that before 3.0.0 drops so we don't have to do a 4.0.0 a few days later

**Comment by mhedgpeth** [comment]
Now that it's set to :kill by default this works. I just tested it.

**Comment by tas50** [comment]
Good to hear @mhedgpeth
