### ISSUE TITLE
If checksum is not correct, chef-client will loop infinitely. 

### ISSUE THREAD

**Issue by trevorghess** [chef-cookbooks/chef_client_updater#51]
### Cookbook version
chef_client_updater 1.1.1

### Chef-client version
chef-12.19.33-1.el6.x86_64

### Platform Details
CentOS 6.8

### Scenario: [What you are trying to achieve and you can't?]
Upgrade chef from 12.19.33 to 12.20.3 using download_url_override.

### Steps to Reproduce: [If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
set chef_client_updater attributes as below(checksum is not correct).
"chef_client_updater": { "version": "12.20.3", "download_url_override": "http://artifactory-instance:8000/artifactory/chef_rpms/rhel/6/x86_64/release/Packages/chef-12.20.3-1.el6.x86_64.rpm", "checksum": "0000000000000000000000000000000000000000000000000000000000000000" }

### Expected Result: [What are you expecting to happen as the consequence of above reproduction steps?]
If checksum is not correct, chef-client is failed and stopped.

### Actual Result: [What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
If checksum is not correct, chef-client is loop infinitely.
please see the attached file.

**Comment by tas50** [comment]
@trevorghess 

So the good news here is we no longer loop given the latest version of this cookbook / mixlib-install. The bad news is we don't fail to install the file. More on that after I dig in a bit more

**Comment by dheerajd-msys** [comment]
@trevorghess 
We are no longer getting loop with latest cookbook. 
```
       [2019-11-29T09:44:38+00:00] FATAL: RuntimeError: chef_client_updater[Install latest Chef] (test::direct_url line 3) had an error: RuntimeError: Error updating chef-client. exit code: 1.
       STDERR:
       STDOUT: el 6 x86_64
       Download URL override specified
       /tmp/install.sh.3446/chef-12.19.36-1.el6.x86_64.rpm not found
       downloading https://packages.chef.io/files/stable/chef/12.19.36/el/6/chef-12.19.36-1.el6.x86_64.rpm
         to file /tmp/install.sh.3446/chef-12.19.36-1.el6.x86_64.rpm
       trying wget...
       Comparing checksum with sha256sum...
       Package checksum mismatch!
       Version: 12.19.36
```
@tas50 do we need anything else to close this issue ?

**Comment by tas50** [comment]
Sounds like we can close this one out to me since we can't repro it anymore
