### ISSUE TITLE
Chef_Client_Updater 3.0.3 exit error

### ISSUE THREAD

**Issue by Magictoys** [chef-cookbooks/chef_client_updater#60]
### Cookbook version
[3.0.3]

### Chef-client version
[12.13.37]

### Platform Details
[Windows 2012 r2 - Redat 5x 6x]

### Scenario:
[the update chef client done  but the cookbook finish with error, but if i restart cookbook all is fine ]

### Steps to Reproduce:
[i start chef-client -o chef_client_updater and i have error message but the chef-client upgrade is work]

  - chef_client_updater (3.0.3)
Installing Cookbook Gems:
Compiling Cookbooks...
[2017-08-11T11:10:28+02:00] INFO: The version of chef-client to install/upgrade/downgrade is : 12.13.37
[2017-08-11T11:10:28+02:00] INFO: Downloading pulp chef-client from http://pulp.cma-cgm.com/chef/chef-client/robby/windows/chef-client-12.13.37-1-x64.msi.....
Converging 1 resources
Recipe: chef_client_updater::default
  * chef_client_updater[update chef-client] action update[2017-08-11T11:10:28+02:00] INFO: Processing chef_client_updater[update chef-client] action update (chef_client_upda

    - remove c:/opscode/chef.upgrade from previous chef-client run
    - upgrade rubygems 2.6.6 to latest[2017-08-11T11:10:45+02:00] INFO: mixlib-install gem not found. Installing now

    * chef_gem[mixlib-install] action install[2017-08-11T11:10:45+02:00] INFO: Processing chef_gem[mixlib-install] action install (c:/chef/cache/cookbooks/chef_client_update
[2017-08-11T11:10:50+02:00] INFO: chef_gem[mixlib-install] installed mixlib-install at >= 3.3.1

      - install version >= 3.3.1 of package mixlib-install
    * chef_gem[mixlib-install] action install[2017-08-11T11:10:50+02:00] INFO: Processing chef_gem[mixlib-install] action install (c:/chef/cache/cookbooks/chef_client_update
 (up to date)

[2017-08-11T11:10:50+02:00] WARN: Skipping final node save because override_runlist was given
[2017-08-11T11:10:50+02:00] INFO: Chef Run complete in 23.221458 seconds
[2017-08-11T11:10:50+02:00] INFO: Skipping removal of unused files from the cache
[0m
Running handlers:
[2017-08-11T11:10:51+02:00] INFO: Running report handlers
Running handlers complete
[2017-08-11T11:10:51+02:00] INFO: Report handlers complete
Chef Client finished, 2/3 resources updated in 29 seconds

the problem is just exit in error but it's work

**Comment by Magictoys** [comment]
It seems to me that the kill function does not work with the redhat 5x 6x ?

**Comment by StuporHero** [comment]
The kill behavior is not supposed to automatically restart chef. That task is left to the service manager, which on RHEL 5/6 does NOT restart chef for you. You will need to use an external process monitor to restart chef on these systems. There is a note about this in the Readme reproduced below:

Init System Caveats
When Chef runs as a service under a system init daemon such as Sys-V or systemd each chef run forks off from the main chef-client process being managed by the init system. For a chef-client upgrade to occur the running chef-client as well as the parent process must be killed, and a new chef-client must start using the updated binaries. This cookbook handles killing the chef-client, but your init system must properly handle starting the service back up. For systemd and upstart this can be handled via configuration, and chef-client cookbook 8.1.1 or later handles this by default. This functionality is not available in sys-v (RHEL 6, Debian 7, and others), so you will need to employ a secondary process such as a monitoring system to start the chef-client service.

**Comment by Magictoys** [comment]
The cookbook in version 2.0.3 works perfectly in all redhat versions.

**Comment by StuporHero** [comment]
I'm not one of the maintainers, so I can't speak for them, but typically incrementing the first number in a version string indicates breaking changes, so you should expect version 3 to work differently than version 2. All I can tell you is that this cookbook is documented to work the way you've described, so you should either stick to using the version you know works or use this version as it is documented.

**Comment by Magictoys** [comment]
Thank you for your help I will wait for the response of the dev.

thank you

**Comment by lamont-granquist** [comment]
you can use `:exec` if it works.  if it does not work, i don't have a solution.

**Comment by Magictoys** [comment]
i test version 3.0.4 and i have same problem but it works ( exit error ) 
CHEF_CLIENT_VERSION = '12.13.37'
DOWNLOAD_URL_OVERRIDE = 'http://pulp.cma-cgm.com/pulp/repos/opt/pulp/cma/rpm'
DOWNLOAD_URL_OVERRIDE_WINDOWS = 'http://pulp.cma-cgm.com/chef/chef-client/robby/windows'
def chef_client_updater_settings
    # stable or current channel
    default['chef_client_updater']['channel'] = 'stable'
    # prevent a newer client "updating" to an older client
    default['chef_client_updater']['prevent_downgrade'] = false
    # the version to install (ex: '12.12.13') or 'latest'
    Chef::Log.info("The version of chef-client to install/upgrade/downgrade is : #{CHEF_CLIENT_VERSION}")
    default['chef_client_updater']['version'] = "#{CHEF_CLIENT_VERSION}"
    # kill the client post install or exec the client post install for non-service based installs
    default['chef_client_updater']['post_install_action'] = 'kill'
end

case node['platform']
   when 'redhat'
   	  # Red Hat Enterprise Linux Server release 7.X
      if (node['platform_version'].include? '7.')
         chef_client_updater_settings
         # the download URL (for use in an air-gapped environment)
         Chef::Log.info("Downloading pulp chef-client from #{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el7.x86_64.rpm.....")
         default['chef_client_updater']['download_url_override'] = "#{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el7.x86_64.rpm"
         # the checksum of the package from "download_url_override"
         default['chef_client_updater']['checksum'] = '99beef40d6574e5a1e37e166b812dc80399c77cd42f239d79f4103591dcc4898'
      end
      # Red Hat Enterprise Linux Server release 6.X
      if (node['platform_version'].include? '6.')
      	 chef_client_updater_settings
      	 # the download URL (for use in an air-gapped environment)
         Chef::Log.info("Downloading pulp chef-client from #{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el6.x86_64.rpm.....")
         default['chef_client_updater']['download_url_override'] = "#{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el6.x86_64.rpm"
         # the checksum of the package from "download_url_override"
         default['chef_client_updater']['checksum'] = '16d908e3d25ec99e4d3abbc080f050c902467de2b481ec226b5e10ccd7062152'
      end
      # Red Hat Enterprise Linux Server release 5.X (64 bits)
      if (node['platform_version'].include? '5.') && if (node['kernel']['machine'].include? 'x86_64')
         chef_client_updater_settings
         # the download URL (for use in an air-gapped environment)
         Chef::Log.info("Downloading pulp chef-client from #{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el5.x86_64.rpm.....")
         default['chef_client_updater']['download_url_override'] = "#{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el5.x86_64.rpm"
         # the checksum of the package from "download_url_override"
         default['chef_client_updater']['checksum'] = 'afc8e0f4c60055cf08ab3914c6ae25e183e234e7efcfa81080339e2986a97e0e'
      end
      end
      # Red Hat Enterprise Linux Server release 5.X (32 bits)
      if (node['platform_version'].include? '5.') && if (node['kernel']['machine'].include? 'i686')
      	 chef_client_updater_settings
         # the download URL (for use in an air-gapped environment)
         Chef::Log.info("Downloading pulp chef-client from #{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el5.i386.rpm.....")
         default['chef_client_updater']['download_url_override'] = "#{DOWNLOAD_URL_OVERRIDE}/chef-#{CHEF_CLIENT_VERSION}-1.el5.i386.rpm"
         # the checksum of the package from "download_url_override"
         default['chef_client_updater']['checksum'] = '4ed7b04b2c62796b637c10a68b9f341023e1333c852fe9133f3d605e75ccbf4a'
      end
      end
   when 'windows'
   	  # Windows
   	  chef_client_updater_settings
   	  # the download URL (for use in an air-gapped environment)
      Chef::Log.info("Downloading pulp chef-client from #{DOWNLOAD_URL_OVERRIDE_WINDOWS}/chef-client-#{CHEF_CLIENT_VERSION}-1-x64.msi.....")
      default['chef_client_updater']['download_url_override'] = "#{DOWNLOAD_URL_OVERRIDE_WINDOWS}/chef-client-#{CHEF_CLIENT_VERSION}-1-x64.msi"
      # the checksum of the package from "download_url_override"
      default['chef_client_updater']['checksum'] = '08906cde0883f9b37deb777b482ff3fad63210139ec49c750c5d167613db9942'
end

**Comment by Magictoys** [comment]
Is it possible to have the function exec & kill that works for REDHAT 5x a

**Comment by Magictoys** [comment]
Is it possible to have the function exec & kill that works for REDHAT 5x & 6x. thanks
