### ISSUE TITLE
Failure to detect installed chef version

### ISSUE THREAD

**Issue by StuporHero** [chef-cookbooks/chef_client_updater#61]
### Cookbook version
3.0.3

### Chef-client version
Tested with 13.0.118, 13.2.20

### Platform Details
oracle-6.9

### Scenario:
The cookbook appears to be failing to correctly detect the installed version of chef and will restart indefinitely in my recipe. I can't seem to reproduce this outside of my recipe because I haven't isolated what in my recipe causes the behavior. I've confirmed that this symptom is not present with version 3.0.2 which at least narrows down which commits could possibly be the culprit.

### Steps to Reproduce:
Unzip [this cookbook](https://github.com/chef-cookbooks/chef_client_updater/files/1217858/server-config.zip) and run kitchen converge on it.

### Expected Result:
chef_client_updater should show (up to date).

### Actual Result:
chef_client_updater updates chef and execs a new chef-client which updates chef and execs a new chef-client etc.

**Comment by tas50** [comment]
What version are you telling the cookbook to update to?

**Comment by StuporHero** [comment]
I've tried '13.0.118', '13.2.20', and '13'.

**Comment by iennae** [comment]
I replicated this issue with your cookbook. It looks like the latest version of this cookbook will resolve your problem. Update your metadata to use 3.0.4 to pull in @tas50 fix.
