### ISSUE TITLE
Allow floating versions

### ISSUE THREAD

**Issue by axos88** [chef-cookbooks/chef_client_updater#7]
### Cookbook version

:latest

### Chef-client version

12.19.36

### Platform Details

N/A

### Scenario:

Allow version specification such as "<13.0.0",  or "~>12.19" etc.

### Expected Result:

Available versions should be match using the known ruby version rules, and the latest version that matches installed.

**Comment by mitom** [comment]
Currently you can specify a version like '12' which will try to install the latest of version 12 the way the omnibus installer works. This will either send chef into a loop where it will keep triggering a new chef client run, which will trigger another update that triggers another chef client run and so on if the post action is `exec`, or it will keep killing the chef run every single time if it's set to `kill` as it seems unable to detect that it's on the right version already.

**Comment by lamont-granquist** [comment]
closing in favor of #17

**Comment by lamont-granquist** [comment]
infinite loop fixed in #22
