### ISSUE TITLE
Add option to restart node after chef-client update.

### ISSUE THREAD

**Issue by timbrown5** [chef-cookbooks/chef_client_updater#71]
We use chef to manage a lot of VMs and we have a scheduled task that runs chef-client on boot - and reboots is there are any installs/updates that might not have completed yet. At the moment this recipe leaves the VMs on, but not doing anything, after the chef-client is updated, which require manual intervention. As such it would be really useful if this recipe would allow us to reboot the target after the chef-client has been updated, so that the run may then continue after a reboot.

Note: We use Windows and Linux (Windows doesn't currently support 'exec', it forces 'kill', with seemingly no workaround - which BTW is REALLY annoying behavior!).

**Comment by tas50** [comment]
@timbrown5 Can you elaborate on the need to reboot the node after the chef client is updated. I haven't heard of anyone rebooting nodes post chef upgrade and that's something I've never done in the environments I managed.

**Comment by timbrown5** [comment]
We use chef in a test environment to manage our test clients and make sure that they have the correct version of our tools installed before we run a test.
We use a CI tool to run our tests, but we found that running chef-client in a CI job causes issues when the chef client needs a reboot (which on windows happens semi-regularly as our tools often install driver updates).
Instead when we start a test we have the CI tool turn the VMs on before we run a job (but after chef has been configured). Then we have chef0client run on logon, and then trigger the connection to the CI tool.
This allows us to make sure chef-client has run successfully before the build job runs.
The problem we with using chef-client-updater to update chef-client is that on Windows it will always fail the chef-client run (which I see the reason for, but it would be nice to be allowed to disable this). From what I can tell can't even use a reboot resource to reboot the node, as this will only run when the chef-client run succeeds, and I don't think I can catch the exit.

Adding a "reboot" option to post_install_action will allow us to integrate this into our current system as instead of leaving the VM on and not connection to CI - which then requires manual intervention to reboot. It will also allow you to keep the current behaviour of not allowing 'exec' option on Windows.

**Comment by timbrown5** [comment]
I have added the option here:
https://github.com/chef-cookbooks/chef_client_updater/compare/master...timbrown5:master
Seems to work for my situation (only tested on windows as I don't have any linux VMs available at the moment).

Note: I tried using reboot resource to schedule the reboot, but this didn't work for me (as it tried to use the new install, which isn't configured for our environment yet).

**Comment by croffe** [comment]
Since this functionality is not required by the updater, wouldn't you be able to accomplish this by notifying the reboot resource?

**Comment by tas50** [comment]
It's tricky since the update resource never actually finishes. It does the kill or the exec mid run.

**Comment by dheerajd-msys** [comment]
Fixture is done in https://github.com/chef-cookbooks/chef_client_updater/pull/78 .

Closing the issue.

Thanks!!
