### ISSUE TITLE
Chef hangs on client downgrade

### ISSUE THREAD

**Issue by pjjohnstone** [chef-cookbooks/chef_client_updater#8]
### Cookbook version
1.0.2

### Chef-client version
12.19.36

### Platform Details
Windows 2012 R2

### Scenario:
Trying to downgrade to 12.5.1

### Steps to Reproduce:
On a chef node running 12.19.36 use the chef_client_updater resource with the prevent_downgrade false option to downgrade to 12.5.1

### Expected Result:
12.19.36 is replaced by 12.5.1 on converge

### Actual Result:
Chef gets stuck waiting for the previous version of chef to stop.  Output:
`10.211.192.112 [2017-04-26T10:37:42+01:00] INFO: Processing chef_client_updater_updater[Install 12.5.1] action update (cloudhouse_chef_node::default line 7)
10.211.192.112 [2017-04-26T10:37:42+01:00] WARN: Replacing ourselves with the new version of Chef to continue the run.
10.211.192.112 [2017-04-26T10:37:45+01:00] WARN: Chef client 2440 is running, will wait for it to finish and then run.`

**Comment by jasonroth** [comment]
We are having the same issue downgrading from 13.0.113 to 12.19.36

**Comment by lamont-granquist** [comment]
hopefully cleaned up by #23 via merging in the changes in #18 

if there's still windows issues after those changes are released, please cut a new issue (even if its the same problem).
