### ISSUE TITLE
Chef terminated during upgrade attempt.

### ISSUE THREAD

**Issue by yurylevin** [chef-cookbooks/chef_client_updater#85]
Hi, there. We are experiencing troubles with Chef client upgrade using `chef_client_updater` cookbook. There are 2 issues:

1) Normally, this cookbook terminates chef client in kitchen, and I cannot solve it according to suggestion `In order to test this cookbook it will be necessary to change the post_install_action to exec from kill.` I try to do it and Chef fails with  error:

```
        Recipe: chef_client_updater::default
          * chef_client_updater[update chef-client] action update
            * chef_gem[mixlib-install] action install
       - install version ~> 3.9 of package mixlib-install
            * powershell_script[name] action runSUCCESS: The scheduled task "Chef_upgrade" has successfully been created.

       - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -Execut
ionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180124-2776-1lq0zy7.ps1"
            - upgrade chef-client 13.5.3 to 13.6.4[2018-01-24T06:50:58-08:00] WARN: post_install_action "exec" not supp
orted for chef-client running forked -- changing to "kill".
      [2018-01-24T06:50:58-08:00] WARN: forcing "exec" to "kill" on windows.
      [2018-01-24T06:50:58-08:00] WARN: New chef-client installed. Forcing chef exit!
```

2) Second issue if it's used in real environment (with post_install_action kill) chef client is aborted and the rest of cookbooks in runlist aren't called. I believe it's caused by line https://github.com/chef-cookbooks/chef_client_updater/blob/58feaf3fca35c6e9de628722e09b156cbce465a3/providers/default.rb#L244

Could you [lease confirm it's expected behavior or bugs?

Platform is Windows 2012. I upgrade chef-client 13.5.3 to 13.6.4. Cookbook version is 3.2.0.

Thanks,
Yury.

**Comment by lamont-granquist** [comment]
this is normal and expected for the `:kill` action.
