### ISSUE TITLE
Readme: the windows service code snippet is strange

### ISSUE THREAD

**Issue by giorgian** [chef-cookbooks/chef_client_updater#90]
In section "Running Chef Client As A Windows Service", the README shows this snippet:

    if Chef::VERSION < node['my_update_cookbook']['desired_version']
      run_chef_task_in_ten_minutes = Time.now + 600

      windows_task 'chef-client-upgrade' do
        cwd 'C:\\opscode\\chef\\bin'
        command 'chef-client'
        run_level :highest
        frequency :once
        start_time "#{run_chef_task_in_ten_minutes.strftime('%H:%M')}"
        action :create
      end
    else
      windows_task 'chef-client-upgrade' do
        cwd 'C:\\opscode\\chef\\bin'
        command 'chef-client'
        run_level :highest
        frequency :once
        start_time "#{run_chef_task_in_ten_minutes.strftime('%H:%M')}"
        action :delete
      end
    end

What should it do? The if and else branches are perfectly identical, with the only difference that in the else branch, the variable `run_chef_task_in_ten_minutes` is nil, so that `run_chef_task_in_ten_minutes.strftime` is guaranteed to raise a NoMethodError.

What am I missing?

**Comment by dheerajd-msys** [comment]
README is updated in https://github.com/chef-cookbooks/chef_client_updater/pull/78.

Closing this issue.
