### ISSUE TITLE
chef_client_updater always schedules update when product_name chefdk

### ISSUE THREAD

**Issue by sardm** [chef-cookbooks/chef_client_updater#95]
### Cookbook version
3.2.4

### Chef-client version
13.6.4, 13.4.19

### Platform Details
Windows 10, Windows 2012r2

### Scenario:
Upgrade chefdk to latest, or specific version.

### Steps to Reproduce:
1. Create role with recipe[chef_client_updater] and add override attr below, run chef-client with role against node.
{
  "chef_client_updater": {
    "product_name": "chefdk",
    "upgrade_delay": 71
  }
}
or for a chefdk version:
{
  "chef_client_updater": {
    "version": "2.4.17"
    "product_name": "chefdk",
    "upgrade_delay": 71
  }
}

### Expected Result:
Install latest chefdk. On subsequent runs only install if there is new version.
or 
With version specified, Install versioned chefdk, and install only when a different version was detected. 

### Actual Result:
Every run tries to install chefdk, scheduling a windows task Chef_upgrade that fails. 
Every subsequent run on the node with this role will fail.

**Comment by bkonick** [comment]
I believe I am seeing this issue also. Trying to test this in kitchen and it just sits in an infinite loop of updating.

**Comment by bkonick** [comment]
More info:

```
ohai chef_packages
[2018-04-02T16:17:02+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
{
  "chef": {
    "version": "13.8.5",
    "chef_root": "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib"
  },
  "ohai": {
    "version": "13.8.0",
    "ohai_root": "/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/ohai-13.8.0/lib/ohai"
  }
}
```

This seems like it will only work for chef-client rather than both chef-client and ChefDK:
https://github.com/chef-cookbooks/chef_client_updater/blob/master/providers/default.rb#L105-L107
https://github.com/chef-cookbooks/chef_client_updater/blob/master/providers/default.rb#L133-L142

**Comment by irvingpop** [comment]
nice investigation @bkonick -  I concur that the `current_version` method is likely the easiest thing to change to something like:

```
def current_version
  node['chef_packages'][new_resource.product_name]['version']
end
```

**Comment by bkonick** [comment]
Thanks @irvingpop! .. I'll play around with that function and see what I can come up with.

Seems like an easier way to go is use actual OS package names rather than this which appears to be looking at the gem. Given that the statement in the readme is support of all platforms with a chef-client package download that might work?

**Comment by irvingpop** [comment]
You're right, I think the Ohai `packages` provider may be more reliable for that.
