### ISSUE TITLE
chef_client_updater fails after chef-client been upgrade

### ISSUE THREAD

**Issue by dabukhader** [chef-cookbooks/chef_client_updater#96]
### Cookbook version
3.2.5
### Chef-client version
[Version of chef-client in your environment]

### Platform Details
Centos 7
### Scenario:
Upgrading Chef-client from 12.20.3 to latest (13.8.5)
### Steps to Reproduce:
We are calling this cookbook a role to update chef client 
`run_list "recipe[xxxx]", "recipe[chef_client_updater::default]"`
Chef run and update the chef-client but it gives an error at the end which shows that the jobs has failed. 
`==> default: [2018-03-14T15:57:11+00:00] WARN: Chef client is running forked with a supervisor. Sending TERM to parent process!
==> default: [2018-03-14T15:57:11+00:00] WARN: New chef-client installed and exit is allowed. Forcing chef exit!
==> default:
==> default:     ================================================================================
==> default:     Error executing action `update` on resource 'chef_client_updater[update chef-client]'
==> default:     ================================================================================
==> default:
==> default:     SystemExit
==> default:     ----------
==> default:     exit
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `exit'
==> default:     /var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:180:in `run_post_install_action'
==> default:     /var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:343:in `block (2 levels) in class_from_file'
==> default:     /var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:342:in `block in class_from_file'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/chef_client_updater/recipes/default.rb
==> default:
==> default:      20: chef_client_updater 'update chef-client' do
==> default:      21:   channel node['chef_client_updater']['channel']
==> default:      22:   version node['chef_client_updater']['version']
==> default:      23:   prevent_downgrade node['chef_client_updater']['prevent_downgrade']
==> default:      24:   post_install_action node['chef_client_updater']['post_install_action']
==> default:      25:   download_url_override node['chef_client_updater']['download_url_override'] if node['chef_client_updater']['download_url_override']
==> default:      26:   checksum node['chef_client_updater']['checksum'] if node['chef_client_updater']['checksum']
==> default:      27:   upgrade_delay node['chef_client_updater']['upgrade_delay'] unless node['chef_client_updater']['upgrade_delay'].nil?
==> default:      28:   product_name node['chef_client_updater']['product_name'] if node['chef_client_updater']['product_name']
==> default:      29: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/chef_client_updater/recipes/default.rb:20:in `from_file'
==> default:
==> default:     chef_client_updater("update chef-client") do
==> default:       action [:update]
==> default:       updated true
==> default:       updated_by_last_action true
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :chef_client_updater
==> default:       cookbook_name "chef_client_updater"
==> default:       recipe_name "default"
==> default:       channel "stable"
==> default:       version "latest"
==> default:       prevent_downgrade false
==> default:       post_install_action "kill"
==> default:       product_name "chef"
==> default:       exec_command "chef-solo"
==> default:       exec_args ["--config", "/tmp/vagrant-chef/solo.rb", "--json-attributes", "/tmp/vagrant-chef/dna.json", "--log_level", "info", "--force-formatter"]
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default: [2018-03-14T15:57:11+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2018-03-14T15:57:11+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2018-03-14T15:57:11+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 33 resources updated in 07 minutes 50 seconds
==> default: [2018-03-14T15:57:11+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2018-03-14T15:57:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2018-03-14T15:57:11+00:00] ERROR: chef_client_updater[update chef-client] (chef_client_updater::default line 20) had an error: SystemExit: exit
==> default: bash: line 4: 19898 Killed                  chef-solo --config /tmp/vagrant-chef/solo.rb --json-attributes /tmp/vagrant-chef/dna.json --log_level info --force-formatter
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.` 

### Expected Result:
We accept that chef would exit with success status not an error. 
------------------------------------------------------------------
When I commented run-post-install. Chef process exit without any error.

**Comment by lamont-granquist** [comment]
this is normal and expected for `post_install_action "kill"`
